export { default as Analytics } from "./Analytics";
export { default as CRM } from "./CRM";
export { default as Ecommerce } from "./Ecommerce";
export { default as ForgotPassword } from "./ForgotPassword";
export { default as InvoiceDetails } from "./InvoiceDetails";
export { default as InvoiceList } from "./InvoiceList";
export { default as Login } from "./Login";
export { default as Message } from "./Message";
export { default as MyAccount } from "./MyAccount";
export { default as Notification } from "./Notification";
export { default as OrderList } from "./OrderList";
export { default as ProductList } from "./ProductList";
export { default as ProductView } from "./ProductView";
export { default as Register } from "./Register";
export { default as Settings } from "./Settings";
export { default as UserList } from "./UserList";
export { default as UserLog } from "./UserLog";
export { default as Devices } from "./Devices";
export { default as UserProfile } from "./UserProfile";
export {default as Editdevices} from  "./Editdevices";
export {default as Edituser} from  "./Edituser";
export {default as MapPage} from  "./MapPage";
export {default as DeviceDashboard} from  "./DeviceDashboard";
export {default as Addresslist} from  "./Addresslist";